### ISSUE TITLE
Acertar os documentos de especificação de requisitos

### ISSUE THREAD

**Issue by ghtravassos** [ESEGroup/IssuesAuthenticatorUrutu#2]
Com base nas indicações dos revisores externos, realizar a correção dos documentos de especificação

**Comment by lucasbarcellosoliveira** [comment]
Documentos corrigidos pela equipe seguindo as orientações dadas pelos revisores. Adicionalmente, informo que a primeira versão do código-fonte também foi disponibilizada.
