### ISSUE TITLE
Atualização dos Artefatos

### ISSUE THREAD

**Issue by alessandrocaetanob** [ESEGroup/IssuesAuthenticatorUrutu#4]
Olá a todos,

Sou o Alessandro, um dos revisores da equipe de VV&T que está trabalhando juntamente com este grupo. Gostaria de solicitar que corrijam os artefatos de acordo com a inspeção realizada para que possamos continuar com o planejamento de testes. Caso tenham alguma dúvida, podem entrar em contato conosco por email ou abrindo issues aqui no Github.

Obrigado

**Comment by lucasbarcellosoliveira** [comment]
Olá, Alessandro!

  Obrigado pelo contato! Efetuamos as correções sugeridas. Os artefatos atualizados se encontram nas pasta Artifacts da branch master, onde estavam antes da revisão. Caso tenhamos esquecido de algo, é só dizer!

     Até breve e obrigado pela ajuda!
