### ISSUE TITLE
Time VV&T: inspecionar artefatos atualizados

### ISSUE THREAD

**Issue by victor0machado** [ESEGroup/IssuesAuthenticatorUrutu#5]

**Comment by ghtravassos** [comment]
Atualizar material sobre VV&t. Nao pude identificar resultados anteriores, embora sei que existem. Atualizar Wiki e conjunto de artefatos de revisao.

**Comment by alessandrocaetanob** [comment]
Abordado na issue #9

**Comment by lucasbarcellosoliveira** [comment]
Feedback do VV&T recebido e material atualizado!
