### ISSUE TITLE
Diagrama de Classes necessita revisao

### ISSUE THREAD

**Issue by ghtravassos** [ESEGroup/IssuesAuthenticatorUrutu#8]
As relacoes nos diagramas de classe estao assumindo totalidade. Isso pode trazer problema. Outra questao diz respeito ao historico com uma relacao de composicao com laboratorio e uma de agregacao com usuario. Isso nao faz sentido. Seria o mesmo historico?

**Comment by alessandrocaetanob** [comment]
Abordado na issue #9

**Comment by lucasbarcellosoliveira** [comment]
OK! Realmente, foi um defeito que não percebemos na revisão anterior. Correções feitas! Obrigado!
