### ISSUE TITLE
Inspeções Release 3

### ISSUE THREAD

**Issue by alessandrocaetanob** [ESEGroup/IssuesAuthenticatorUrutu#9]
### Inspeções

Olá, estou subindo o checklist com as inspeções e as correções que precisam ser feitas para a Release 3. Foram poucas as inconsistências encontradas, desta forma da para corrigir tudo bem facilmente.

[Inspeção da Descrição de Casos de Uso - Release 3](https://github.com/ESEGroup/IssuesAuthenticatorUrutu/files/1523941/Inspecao.da.Descricao.de.Casos.de.Uso.-.Release.3.docx)
[Inspeção do Diagrama de Casos de Uso - Release 3](https://github.com/ESEGroup/IssuesAuthenticatorUrutu/files/1523942/Inspecao.do.Diagrama.de.Casos.de.Uso.-.Release.3.docx)

Basicamente, o único problema encontrado é com o caso de uso de CRUD. Neste [link](https://pt.stackoverflow.com/questions/20885/n%C3%ADvel-de-detalhamento-de-casos-de-uso) do StackOverflow o detalhamento de casos de uso deste tipo são discutidos e é apresentada uma boa solução.

### A respeito do diagrama de classes

- A cardinalidade da relação entre as classes que representam o Issues Monitoring o Delegado deve ser 1 para 0..* . O Issues Monitoring pode ser instanciado sem um objeto da classe Delegado, mas o Delegado não pode ser instanciado sem um objeto da classe Issues Monitoring.

- A agregação entre usuário e histórico não faz sentido, remover.

**Comment by lucasbarcellosoliveira** [comment]
Muito obrigado, Alessandro! As correções sugeridas foram feitas e agora se encontram disponíveis nas novas versões dos documentos citados. Agradecemos o _feedback_.

**Comment by alessandrocaetanob** [comment]
Obrigado, @lucasbarcellosoliveira
